server:
  # 服务端口
  port: 8081
spring:
  application:
    name: order-provider
# dubbo 相关配置(dubbo 的配置不再以 Spring 开头)
dubbo:
  application:
    # 应用名称
    name: order-provider
    qosEnable: false
  scan:
    # 接口实现者（服务实现）包
    base-packages: com.xiushang.admin.service
  # 注册中心信息
  registry:
    address: nacos://121.37.171.85:8848
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
    port: -1
