# 端口
server:
  port: 8092
  servlet:
    register-default-servlet: true

spring:
  profiles:
    active: @env.id@
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
  # 配置session共享
  session:
    store-type: redis
    timeout: 3600000 #半小时过期 60*60*1000
  # 关闭spring data 的redis仓库
  data:
    redis:
      repositories:
        enabled: false
