# 端口
server:
  port: 8091
  servlet:
    register-default-servlet: true

spring:
  profiles:
    active: @env.id@
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
  # 配置session共享
  session:
    store-type: redis
    timeout: 3600000 #半小时过期 60*60*1000
  # 关闭spring data 的redis仓库
  data:
    redis:
      repositories:
        enabled: false

knife4j:
  enable: false

#oauth path
oauth:
  client: #管理员客户端前缀
    prex: xiushang
  path:
    url: /api/


secure:
  ignored:
    urls: #安全路径白名单
      - /
      - /doc.html
      - /swagger-resources/**
      - /v2/api-docs
      - /v2/api-docs-ext
      - /webjars/**
      #- /druid/**
      - /favicon.ico
      - /favicon.png
      - /captcha.jpg
      - /login
      - /logout
      - /captcha
      - /authentication/**
      - /oauthLogin
      #- static
      - /test/**
