server:
  port: 8082
spring:
  application:
    name: order-consumer
    qosEnable: false
  registry:
    address: nacos://121.37.171.85:8848
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
    port: -1
